### PR TITLE
Fixed #44

### LINKED ISSUE #44: Crash in flutter v1.5.9
file:///Users/dingzuhua/.pub-cache/hosted/pub.flutter-io.cn/flutter_image_compress-0.4.0/lib/flutter_image_compress.dart:188:16: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
     - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/dingzuhua/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
    Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
          context: 'image load failed ',

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.5.9-pre.196, on Mac OS X 10.14.4 18E226, locale
    zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[✓] Connected device (1 available)

• No issues found!

### PR DESCRIPTION
**Pull request by vanelizarov**
Fixed #44 
This error occurs on master channel 

`flutter doctor -v`:
```
[✓] Flutter (Channel master, v1.6.1-pre.32, on Mac OS X 10.14.5 18F131a, locale en-RU)
    • Flutter version 1.6.1-pre.32 at /Users/vanelizarov/flutter
    • Framework revision 4aaeb4e11f (7 hours ago), 2019-05-16 23:52:38 -0400
    • Engine revision 065fe5b210
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 5ffff98440)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/vanelizarov/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone Xʀ                 • D71EC0B3-B4A2-41DB-9C0C-878DCDD474E3 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

I think it will be correct to merge this PR when that `FlutterErrorDetails` API change lands on `stable`

### CODE REVIEW

**Comment by CaiJingLong** [comment]
Now, stable version is 1.5.4-hotfix2. 
You can see  stable version at https://flutter.dev/docs/development/tools/sdk/releases?tab=macos.

The `context` [link](https://github.com/flutter/flutter/blob/7a4c33425ddd78c54aba07d86f3f9a4a0051769b/packages/flutter/lib/src/foundation/assertions.dart#L67)

So , I will merge this PR, but I may need to wait until I query the specific version number to determine the constraints of flutter SDK.

**Comment by CaiJingLong** [comment]
I find the change at the [commit](https://github.com/flutter/flutter/commit/63aa5b3647dbd912a02f7545fc0101003cb3adc4).
Also, version 1.5.9 seems to have been officially removed, so I'll set the flutter sdk constraint to 1.6.0.

File: lib/flutter_image_compress.dart [hunk 1]
```diff
@@ -185,7 +185,7 @@ Future<ImageInfo> getImageInfo(BuildContext context, ImageProvider provider,
   void errorListener(dynamic exception, StackTrace stackTrace) {
     completer.complete(null);
     FlutterError.reportError(new FlutterErrorDetails(
-      context: 'image load failed ',
+      context: DiagnosticsNode.message('image load failed '),
```
Comment (CaiJingLong) [inline lib/flutter_image_compress.dart]: I upgrade version to 1.6.0.
The DiagnosticsNode is need import package.

**Comment by CaiJingLong** [comment]
Because you didn't reply to my review, I would merge and import the libraries I should have.

**Comment by vanelizarov** [comment]
@CaiJingLong sorry, I’ve missed notification.
Thanks!
